apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-provisioning
  labels:
    app: demo
spec:
  accessModes:
    - ReadWriteOnce # This limits the number of containers can mount the PV
  resources:
    requests:
      storage: 5Gi #5 GB
