apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    stack: logging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G 