apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: esimonetti/sugardockerized:php7.1-apache-1.16
          name: sugar-web
          ports:
            - containerPort: 80
          volumeMounts:
            - name: sugarvol
              mountPath: /var/www/html
          env:
            - name: APACHE_RUN_USER
              value: "sugar"
            - name: APACHE_RUN_GROUP
              value: "sugar"
        - name: permissions
          image: esimonetti/sugardockerized:permissions-1.17
          volumeMounts:
            - name: sugarvol
              mountPath: /var/www/html
      volumes:
        - name: sugarvol
          hostPath:
            path: /Users/vkobilanksy/jx-sugar-docker/data/app/sugar
