apiVersion: batch/v1
kind: Job
metadata:
  name: sugar-mount
spec:
  template:
    metadata:
      name: sugar-mount
    spec:
      containers:
        - image: gcr.io/sv-courses-243217/bitbucket.org/alexandru_cicioc/sugar-mount:e875613
          name: sugar-mount
          volumeMounts:
            - mountPath: /sugar_mount
              name: nfs
              subPath: sugar_new
      restartPolicy: Never
      volumes:
        - name: nfs
          nfs:
            # TODO figure out how to connect using a host, nfs-server doesn't work
            server: 10.12.0.90
            path: /
