apiVersion: v1
kind: Service
metadata:
  name: sugar-elastic
  labels:
    service: sugar-elastic
spec:
  type: NodePort
  selector:
    component: sugar-elastic
  ports:
  - port: 9200
    targetPort: 9200
